# Generated by Django 5.0.2 on 2024-03-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('LICENCIA POR LARGO TRATAMIENTO', 'LICENCIA POR LARGO TRATAMIENTO'), ('JUBILACION EN TRAMITE', 'JUBILACION EN TRAMITE'), ('BAJA O RETIRADO', 'BAJA O RETIRADO'), ('LICENCIA POR MATERNIDAD', 'LICENCIA POR MATERNIDAD')], default='ACTIVO', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='province',
            name='number_id',
            field=models.CharField(max_length=2, unique=True, verbose_name='Numero de Identificación'),
        ),
        migrations.AlterField(
            model_name='province',
            name='province',
            field=models.CharField(max_length=50, unique=True, verbose_name='Provincia'),
        ),
    ]
