# Generated by Django 5.0.2 on 2024-03-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('BAJA O RETIRADO', 'BAJA O RETIRADO'), ('JUBILACION EN TRAMITE', 'JUBILACION EN TRAMITE'), ('ACTIVO', 'ACTIVO'), ('LICENCIA POR LARGO TRATAMIENTO', 'LICENCIA POR LARGO TRATAMIENTO'), ('LICENCIA POR MATERNIDAD', 'LICENCIA POR MATERNIDAD')], default='ACTIVO', max_length=30, verbose_name='Estado'),
        ),
    ]
