# Generated by Django 5.0.2 on 2024-03-11 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0004_alter_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='active',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='computer',
            name='operational',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='imgprinterdevice',
            name='active',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='imgprinterdevice',
            name='operational',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='monitor',
            name='active',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('BAJA O RETIRADO', 'BAJA O RETIRADO'), ('LICENCIA POR LARGO TRATAMIENTO', 'LICENCIA POR LARGO TRATAMIENTO'), ('ACTIVO', 'ACTIVO'), ('LICENCIA POR MATERNIDAD', 'LICENCIA POR MATERNIDAD'), ('JUBILACION EN TRAMITE', 'JUBILACION EN TRAMITE')], default='ACTIVO', max_length=30, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational', models.BooleanField(default=1)),
                ('active', models.BooleanField(default=1)),
                ('last_review', models.DateField(verbose_name='Última Revision')),
                ('serial_k', models.CharField(max_length=20, verbose_name='Número de Serie')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
                ('computer_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyboard_computer', to='sh.computer', verbose_name='Computadora Asignada')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyboard_model', to='sh.model', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Teclado',
                'verbose_name_plural': 'Teclados',
                'db_table': 'teclados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational', models.BooleanField(default=1)),
                ('active', models.BooleanField(default=1)),
                ('last_review', models.DateField(verbose_name='Última Revision')),
                ('serial_mouse', models.CharField(max_length=20, verbose_name='Número de Serie')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
                ('computer_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouse_computer', to='sh.computer', verbose_name='Computadora Asignada')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouse_model', to='sh.model', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Mouse',
                'verbose_name_plural': 'Mouses',
                'db_table': 'mouses',
                'ordering': ['id'],
            },
        ),
    ]
