# Generated by Django 5.0.2 on 2024-03-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0004_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('LICENCIA POR LARGO TRATAMIENTO', 'LICENCIA POR LARGO TRATAMIENTO'), ('BAJA O RETIRADO', 'BAJA O RETIRADO'), ('LICENCIA POR MATERNIDAD', 'LICENCIA POR MATERNIDAD'), ('JUBILACION EN TRAMITE', 'JUBILACION EN TRAMITE')], default='ACTIVO', max_length=30, verbose_name='Estado'),
        ),
    ]
