# Generated by Django 5.0.2 on 2024-03-11 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0005_computer_active_computer_operational_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouse',
            name='computer_assigned',
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='model',
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('LICENCIA POR LARGO TRATAMIENTO', 'LICENCIA POR LARGO TRATAMIENTO'), ('JUBILACION EN TRAMITE', 'JUBILACION EN TRAMITE'), ('BAJA O RETIRADO', 'BAJA O RETIRADO'), ('LICENCIA POR MATERNIDAD', 'LICENCIA POR MATERNIDAD')], default='ACTIVO', max_length=30, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Peripherals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational', models.BooleanField(default=1)),
                ('active', models.BooleanField(default=1)),
                ('last_review', models.DateField(verbose_name='Última Revision')),
                ('serial_per', models.CharField(max_length=20, verbose_name='Número de Serie')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Última Modificación')),
                ('computer_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peripherals_computer', to='sh.computer', verbose_name='Computadora Asignada')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peripherals_model', to='sh.model', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Periferico',
                'verbose_name_plural': 'Perifericos',
                'db_table': 'perifericos',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Keyboard',
        ),
        migrations.DeleteModel(
            name='Mouse',
        ),
    ]
