# Generated by Django 5.0.2 on 2024-03-12 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0005_alter_employee_status'),
        ('sh', '0006_remove_mouse_computer_assigned_remove_mouse_model_and_more'),
    ]

    operations = [
    ]
