# Generated by Django 5.0.2 on 2024-03-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sh', '0008_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('BAJA O RETIRADO', 'BAJA O RETIRADO'), ('JUBILACION EN TRAMITE', 'JUBILACION EN TRAMITE'), ('LICENCIA POR MATERNIDAD', 'LICENCIA POR MATERNIDAD'), ('LICENCIA POR LARGO TRATAMIENTO', 'LICENCIA POR LARGO TRATAMIENTO'), ('ACTIVO', 'ACTIVO')], default='ACTIVO', max_length=30, verbose_name='Estado'),
        ),
    ]
